[build]
  publish = "_site/"
  functions = "functions/"
  command = "cd func && npm install && cd .. && netlify-lambda build func"
  environment = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }

[context.production]
  environment = { NODE_ENV = "production", NPM_CONFIG_PRODUCTION = "false" }
